### ISSUE TITLE
No longer working due to dependency on Request Module

### ISSUE THREAD

**Issue by shak4031** [qistoph/MMM-MyCommute#28]
This module is no longer working due to dependencies on deprecated modules like "request".

**Comment by qistoph** [comment]
I'm currently unable to work on an update. A PR would be most welcome

**Comment by fribse** [comment]
I see this as well with the new 2.18 of MM (and thus the update of node.js):

```
0|MagicMirror  | [13.02.2022 12:48.21.931] [ERROR] App threw an error during load
0|MagicMirror  | [13.02.2022 12:48.21.940] [ERROR] Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-MyCommute/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
0|MagicMirror  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:94:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MyCommute/node_helper.js:9:17)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|MagicMirror  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
0|MagicMirror  | [13.02.2022 12:48.21.945] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [13.02.2022 12:48.21.968] [ERROR]
0|MagicMirror  | Error: Cannot find module 'request'

```

Sigh, another dead module.

**Comment by qistoph** [comment]
A quick fix is probably to install `requests` yourself. As said before, a PR is most welcome.

The great thing with open source is that you can (easily) fix any issues. As times change people aren't always as committed to keeping stuff up-to-date. Also, this module has been running on my mirror for years and still is.

I'll try to look into this issue, but don't have the time I used to have for such hobby projects and have always hoped that sharing my work would encourage others to contribute. The increasing amount of complaints and requests is making me reconsider

**Comment by fribse** [comment]
No problem, just so sad, but I do understand the time constraints, I live with them every day 😄

**Comment by fribse** [comment]
I got it working today byu adding the request package, so that's progress :-)
